apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-demo-staging
  namespace: argocd
spec:
  destination:
    namespace: argocd-demo-staging
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/demo-app/overlays/staging1
    repoURL: https://github.com/PrachiMittal2016/argocd-demo-deploy
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
