apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: demo
 
configurations:
  - https://argoproj.github.io/argo-rollouts/features/kustomize/rollout-transform.yaml
  
resources:
- ./rollout.yaml
- ./service-active.yaml
- ./service-preview.yaml
